---
title: '**Assignment 2: Web scrapping/Data Wrangling in R**'
author: '**Suman Paudel 33**'
date: "`r Sys.Date()`"
output:
  html_document:
    theme:
      base_font:
        google: kate
      heading_font:
        google: Proza Libre
    highlight: tango
  pdf_document: 
    highlight: pygments
---

[GitHub Repository](https://github.com/sumanpaudel1997/R-For-Data-Science/tree/main)

### [ <b> Code Execution and Output/Interpretation of Session 7</b>]{style="color:#d30000"}

#### What is a “package” in R?

-   In R, the fundamental unit of shareable code/function is the package.
-   A package bundles together code, data, documentation, and tests, and is easy to share with others.
-   The public clearing house for R packages is the Comprehensive R Archive Network or `CRAN`. The details about the packages can be found at CRAN.

#### How to install, use and get help about any package from CRAN?

-   We can install packages of CRAN in R using: **`install.packages("packagename")`**\
    For example: **`install.packages("dplyr")`**

-   We can then use the installed packages in R using:\
    **`library(packagename)`**\
    **`e.g. library(dplyr)`**

-   We can get help on the installed packages in R using:\
    **`?packagement`** or **`help(package = "packagement")`**\
    **`e.g. ?dplyr`** OR **`help(package = "dplyr")`**

#### How to develop a package in R?  

\ <https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/>

-   Step 0: Packages you will need
-   Step 1: Creating your package directory
-   Step 2: Add functions
-   Step 3: Add documentation
-   Step 4: Process your documentation
-   Step 5: Install
-   Step 6: Make a package GitHub repo (Bonus!)
-   Step 7: Infinity- Iterate

#### Reading (Import) data in R/R Studio:

-   Text files: R base, readr etc
-   Excel files: readXL, openxls etc.
-   SPSS, Stata, SAS files: foreign, haven etc.

#### Reading data in R/R Studio

-   JSON files: rjason, jsonlite, RJSONIO etc.

#### To install the library to work on josn files.
